FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias globales
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar carpeta extract completa
COPY 1.extract/ ./1.extract/

WORKDIR /app/1.extract

CMD ["python", "run_extract.py"]

