FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar carpeta extract y archivos necesarios
COPY 2.transform/ .

WORKDIR /app

CMD ["python", "run_transform.py"]
